services:
  app:
    build:
      context: node
    container_name: app
    command: ["node", "index.js"]
    entrypoint: dockerize -wait tcp://db:3306 --timeout 30s && docker-entrypoint.sh
    tty: true
    networks:
      - custom-network
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    
  db:
    image: mysql:9.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - custom-network
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  custom-network:
    driver: bridge